version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.5
  aws-cli: circleci/aws-cli@0.1.6

_defaults: &defaults
  # machine:
  #   docker_layer_caching: false
  docker:
    - image: openjdk:8
      environment:
        SBT_VERSION: 1.3.12
    - image: multani/nomad
      command:
        - agent
        - -dev
      environment:
        NOMAD_LOCAL_CONFIG: |
          datacenter = "${REGION}"
          region     = "${DATACENTER}"

          data_dir = "/nomad/data/"

          bind_addr = "0.0.0.0"

          advertise {
            http = "{{ GetPrivateIP }}:4646"
            rpc  = "{{ GetPrivateIP }}:4647"
            serf = "{{ GetPrivateIP }}:4648"
          }
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3000m
    SBT_OPTS: -Xmx2000m
    TERM: dumb
_install-sbt: &install-sbt |
  apt update && apt install -y curl
  curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
  dpkg -i sbt-$SBT_VERSION.deb
  rm sbt-$SBT_VERSION.deb
  apt-get clean && apt-get autoclean

workflows:
  version: 2
  development:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish-snapshot:
          context: nexus
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish:
          context: nexus
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Get sbt binary
          command: *install-sbt
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            - v2-dependencies-
      - run:
          name: Compile
          command: |
            cat /dev/null | sbt +validate
      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt
            - target
          key: v2-dependencies-{{ checksum "build.sbt" }}

  publish:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Get sbt binary
        command: *install-sbt
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release version and bump snapshot
        command: cat /dev/null | sbt ci-release


  publish-snapshot:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Get sbt binary
        command: *install-sbt
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release version and bump snapshot
        command: cat /dev/null | sbt ci-release